### ISSUE TITLE
C++ Library Tips

### ISSUE THREAD

**Issue by ghost** [FFF-Fox/linear-algebra#1]
Hey there!!! I saw you just pushed this repository online and after taking a close look at the nice work you did, I would like to point some things out that might help you develop this library.

- Keep a self-explanatory folder structure.
- Put your library under your own namespaces.
- Write examples that showcase features of your library.
- Write proper documentation (at some point in the future :P).
- Write Unit Tests (You can use Catch2 C++ Testing Framework).
- Consider using a Continuous Integration service like Travis CI for running the tests you made.
- Create a README.md file :) put some nice photo or description.

If you would like my cooperation I would be willing to help.

**Comment by georgetz15** [comment]
@xorz57, your feedback is most welcome! I will keep an eye for what was suggested and try to implement some of the suggestions you have listed.

The purpose of this repository is to brush up on my C++ knowledge and implement things that I learn.

What I have in mind is to make a minimal linear algebra library, with some basic operations. If you are interested in collaborating with ideas/suggestions/code please let me know via e-mail :)
